source "https://rubygems.org"

# gem "jekyll", "~> 3.7.2"
gem "minima", "~> 2.1.1"

group :jekyll_plugins do
  gem "github-pages"
  # gem "jekyll-feed", "~> 0.6"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1.0" if Gem.win_platform?

