source "https://rubygems.org"

gem "jekyll", ">= 3.6.3"
gem "minima", ">= 2.1.1"
gem "nokogiri", ">= 1.8.5"
gem "rubyzip", ">= 1.2.2"
gem "ffi", ">= 1.9.24"

group :jekyll_plugins do
  gem "github-pages"
  # gem "jekyll-feed", "~> 0.6"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1.0" if Gem.win_platform?

